### ISSUE TITLE
Error on undefined index in getInMostAppropriateUnits()

### ISSUE THREAD

**Issue by mrimann** [webignition/readable-duration#2]
We've ran into an issue wile using `getInMostAppropriateUnits()` as it internally calls `roundUpUnitValues()` and on line 444 an array index is accessed that is not set, which raises an Exception.

Our solution was to modify the line from
```
if ($unitValue['value'] == $this->unitThresholds[$unitValue['unit']]) {
```

to: 

```
if (isset($this->unitThresholds[$unitValue['unit']]) && $unitValue['value'] == $this->unitThresholds[$unitValue['unit']]) {
```

This just adds a safeguard to check if the array index is set before it's accessed.

Could this maybe get added to the package? Would be cool!

**Comment by webignition** [comment]
Cool, thanks for the heads up!

Adding a fix for that sounds plausible, I'll look into that now.

**Comment by webignition** [comment]
Wow, looks like I've not touched this package in centuries.

I'm going to update to use PSR4 autoloading, PSR2 CS and will ramp up the test coverage. In doing so I can't miss the bug and I'll likely catch other oddities.

**Comment by webignition** [comment]
Should be all OK now in [v0.3](https://github.com/webignition/readable-duration/releases/tag/0.3)

**Comment by mrimann** [comment]
Wow, THANKS for the super-fast feedback **and** solution! Just updated to v0.3 and it works as expected.

**Comment by webignition** [comment]
@mrimann No worries, glad to help
